/**
 * Client-side taxonomy dataset access + pure search/rank helpers for the
 * category picker.
 *
 * The dataset (`/taxonomy.json`) is OUR static build artifact, generated by
 * `scripts/build-taxonomy.mjs` from Shopify's Standard Product Taxonomy. It is
 * lazy-loaded (not in the initial bundle) and cached at module level so it
 * fetches at most once per session — this is our own data, not search results,
 * so caching it is fine and compliant.
 */

import metaRaw from "./taxonomy-meta.json";

/** A single taxonomy node. `fullName` is derived, not shipped (see build-taxonomy.mjs). */
export interface TaxonomyNode {
  gid: string;
  name: string;
  parentGid: string | null;
  level: number;
}

export interface TaxonomyMeta {
  tag: string;
  version: string;
  count: number;
  generatedFrom: string;
}

export const TAXONOMY_META = metaRaw as TaxonomyMeta;

/** Prebuilt indexes over the dataset, for O(1) lookups and browse navigation. */
export interface TaxonomyIndex {
  nodes: TaxonomyNode[];
  byGid: Map<string, TaxonomyNode>;
  childrenOf: Map<string | null, TaxonomyNode[]>;
  roots: TaxonomyNode[];
}

/** A search result carrying its computed breadcrumb path and match score. */
export interface TaxonomyResult {
  node: TaxonomyNode;
  fullName: string;
  score: number;
}

const DATA_URL = "/taxonomy.json";

// ── module-level cache ────────────────────────────────────────────────────
let cache: TaxonomyIndex | null = null;
let inflight: Promise<TaxonomyIndex> | null = null;

/** Build lookup indexes from a flat node list. */
export function buildIndex(nodes: TaxonomyNode[]): TaxonomyIndex {
  const byGid = new Map<string, TaxonomyNode>();
  const childrenOf = new Map<string | null, TaxonomyNode[]>();
  for (const node of nodes) {
    byGid.set(node.gid, node);
    const key = node.parentGid;
    const bucket = childrenOf.get(key);
    if (bucket) bucket.push(node);
    else childrenOf.set(key, [node]);
  }
  // Alphabetize children/roots for a stable browse order.
  for (const bucket of childrenOf.values()) {
    bucket.sort((a, b) => a.name.localeCompare(b.name));
  }
  const roots = childrenOf.get(null) ?? [];
  return { nodes, byGid, childrenOf, roots };
}

/**
 * Lazy-load the taxonomy dataset once per session. Subsequent calls resolve
 * from the module-level cache without re-fetching.
 */
export async function loadTaxonomy(
  signal?: AbortSignal,
): Promise<TaxonomyIndex> {
  if (cache) return cache;
  if (inflight) return inflight;
  inflight = (async () => {
    const res = await fetch(DATA_URL, { signal });
    if (!res.ok) {
      throw new Error(`Failed to load taxonomy: HTTP ${res.status}`);
    }
    const nodes = (await res.json()) as TaxonomyNode[];
    cache = buildIndex(nodes);
    return cache;
  })();
  try {
    return await inflight;
  } finally {
    inflight = null;
  }
}

/** Synchronous accessor for the cached index (null until `loadTaxonomy` resolves). */
export function getCachedTaxonomy(): TaxonomyIndex | null {
  return cache;
}

/** Build the breadcrumb path ("A > B > C") for a node by walking its parent chain. */
export function breadcrumb(
  gid: string,
  byGid: Map<string, TaxonomyNode>,
): string {
  const parts: string[] = [];
  let current: TaxonomyNode | undefined = byGid.get(gid);
  let guard = 0;
  while (current && guard < 32) {
    parts.unshift(current.name);
    current = current.parentGid ? byGid.get(current.parentGid) : undefined;
    guard += 1;
  }
  return parts.join(" > ");
}

// ── pure search / rank ──────────────────────────────────────────────────────

/** Normalize for case/diacritic-insensitive matching. */
function normalize(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}

/**
 * Score a node against a normalized query. Higher is better; 0 means no match.
 * Ranking: exact name > name prefix > name word-boundary > fullName substring.
 * Pure and dependency-free so it can be unit-tested in isolation.
 */
export function scoreNode(
  name: string,
  fullName: string,
  normalizedQuery: string,
): number {
  if (normalizedQuery === "") return 0;
  const n = normalize(name);
  const f = normalize(fullName);

  if (n === normalizedQuery) return 1000;
  if (n.startsWith(normalizedQuery)) return 800;

  // Word-boundary match within the leaf name (e.g. "phones" in "Headphones"
  // won't hit, but "cell" in "Cell Phones" will).
  const nameWordBoundary = new RegExp(`\\b${escapeRegExp(normalizedQuery)}`);
  if (nameWordBoundary.test(n)) return 600;

  // Substring anywhere in the leaf name.
  if (n.includes(normalizedQuery)) return 400;

  // Match somewhere along the breadcrumb path.
  if (f.includes(normalizedQuery)) return 200;

  return 0;
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Search the taxonomy for a query, returning ranked results with breadcrumbs.
 * Caps at `limit` results. Ties broken by shallower level then name.
 */
export function searchTaxonomy(
  index: TaxonomyIndex,
  query: string,
  limit = 50,
): TaxonomyResult[] {
  const q = normalize(query.trim());
  if (q === "") return [];
  const results: TaxonomyResult[] = [];
  for (const node of index.nodes) {
    const fullName = breadcrumb(node.gid, index.byGid);
    const score = scoreNode(node.name, fullName, q);
    if (score > 0) results.push({ node, fullName, score });
  }
  results.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    if (a.node.level !== b.node.level) return a.node.level - b.node.level;
    return a.node.name.localeCompare(b.node.name);
  });
  return results.slice(0, limit);
}
